name: dl2
channels:
  - pytorch
  - conda-forge
  - defaults
  - huggingface
dependencies:
  # python
  - python=3.9.12
  # pytorch
  - pytorch=1.11.0
  - pytorch-lightning=1.6.3
  - torchvision=0.12.0
  - cudatoolkit=11.3.1
  # hugging face
  - transformers=4.16.2 
  # misc
  - jupyter=1.0.0
