name: dl2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # python
  - python=3.9.12
  - pip=22.0.4
  # pytorch
  - pytorch=1.11.0
  - pytorch-lightning=1.6.3
  - torchvision=0.12.0
  # misc
  - jupyter=1.0.0
  - pip:
    - opencv-python==4.5.5.64
    - wandb==0.12.16
    - transformers==4.19.2
    - grad-cam==1.3.9
