#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --gres=gpu:1
#SBATCH --job-name=Patch-DiffMask
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=48:00:00
#SBATCH --mem=100000M
#SBATCH --output=lisa/outputs/patch_diffmask_train_%A_%a.out

module purge
module load 2021
module load Anaconda3/2021.05

source activate dl2

srun python -u code/main.py --enable_progress_bar --batch_size=64 --num_epochs 60 --array_param $1 --num_workers=16